#define UNAME      "Linux x86_64 GNU/Linux"
/* config.h
 * This file was automatically generated by unix/tfconfig.
 */
#define PLATFORM_UNIX
#define LIBDIR     "/usr/share/games/tf"
#define MAILDIR    "/var/spool/mail"
#define UNISTD_H <unistd.h>
#define STDLIB_H <stdlib.h>
#define STRING_H <string.h>
#define MEMORY_H <memory.h>
#define SYS_SELECT_H <sys/select.h>
#define LOCALE_H <locale.h>
#define NETINET_IN_H <netinet/in.h>
#define ARPA_INET_H <arpa/inet.h>
#define NETDB_H <netdb.h>
#define HAVE_PWD_H
#define MUDCOMPRESS
#define HAVE_STDARG
#define HAVE_bcopy
#define HAVE_bsearch
#define HAVE_bzero
#define HAVE_connect
#define HAVE_fileno
#define HAVE_getcwd
#define HAVE_gethostbyname
#define HAVE_getpwnam
#define HAVE_gettimeofday
#undef  HAVE_getwd
#define HAVE_h_errno
#define HAVE_hstrerror
#define HAVE_index
#define HAVE_kill
#define HAVE_memcpy
#define HAVE_memset
#define HAVE_raise
#define HAVE_setlocale
#define HAVE_sigaction
#define HAVE_srand
#define HAVE_srandom
#define HAVE_strcasecmp
#define HAVE_strchr
#undef  HAVE_strcmpi
#define HAVE_strcspn
#define HAVE_strerror
#define HAVE_strftime
#undef  HAVE_stricmp
#define HAVE_strstr
#define HAVE_strtod
#define HAVE_strtol
#define HAVE_tzset
#define HAVE_waitpid
#define CASE_OK
#define RETSIG void
#define TIME_T time_t
#define TERMCAP
#define USE_TERMIOS
